name: 'hw_fifa_dbt'
version: '1.0.0'

profile: 'hw_fifa_dbt'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  hw_fifa_dbt:
    stage:
      +materialized: table
      +schema: stage
    intermediate:
      +materialized: table
      +schema: intermediate
    mart:
      +materialized: view
      +schema: mart
    malformed:
      +materialized: view
      +schema: malformed
